// ============================================================================
//  STORY SCRIPT  —  "STATIC: A Killing Game"
//  Scene format consumed by engine.js. Each scene is an array of beats.
//  Beat kinds:
//    {s, who, t}          dialogue: sprite charId (s), speaker name (who), text (t)
//    {t}                  narration (no speaker)
//    {bg}                 change background class
//    {sfx}                screen flash effect: "shake","flash","glitch"
//    {choices:[{t,go}]}   branching choice -> jump to label
//    {go}                 unconditional jump to scene label
//    {give}               award a Truth Bullet id (logbook)
//    {investigate}        investigation hub (uses scene's spots)
//    {trial}              run a class-trial sequence (id into TRIALS)
//    {unlock:"freetime"}  open the free-time hub
//    {end}                return to title
// ============================================================================

const STORY = {

  // -------------------------------------------------------------- PROLOGUE
  prologue: [
    { bg:"bg-dark" },
    { t:"Cold tile against your cheek. The hum of a fluorescent light that's been left on too long." },
    { t:"You don't remember lying down. You don't remember the room. You don't remember—" },
    { sfx:"glitch" },
    { t:"—your own talent. There's a gap where it should be, smooth as a worn coin." },
    { s:"protagonist", who:"You", t:"...Where is this?" },
    { bg:"bg-studio" },
    { t:"You're in what looks like an abandoned broadcast studio. Padded walls. Dead microphones hanging like fruit. A red ON AIR sign, unlit." },
    { t:"Nineteen others are already awake. You make twenty-one." },
    { sfx:"flash" },
    { s:"static", who:"???", t:"GOOOOOOD EVENING, listeners! And welcome — to the only show that matters!" },
    { t:"Something drops from the rafters and lands on the producer's desk. A creature. Half vintage microphone, half something with too many teeth. One eye is a glowing red recording light." },
    { s:"static", who:"STATIC", t:"I'm STATIC — your host, your producer, your biggest fan! And YOU are my cast. Twenty-one Ultimates, one studio, and a premise the audience is going to DIE for." },
    { s:"sienna", who:"Sienna Fox", t:"Okay, that's an incredible cold open, I have to give it that." },
    { s:"declan", who:"Declan Cross", t:"Speak for yourself." },
    { s:"static", who:"STATIC", t:"The rules are simple, kittens. You live here now. Forever! UNLESS — you want to graduate." },
    { s:"static", who:"STATIC", t:"To graduate, you only have to do one teensy little thing: kill another cast member. And get away with it." },
    { sfx:"shake" },
    { s:"jasmine", who:"Jasmine Sterling", t:"...I'm sorry. Say that again, with the smile this time." },
    { s:"static", who:"STATIC", t:"After every murder, we hold a CLASS TRIAL! You debate, you accuse, you VOTE. Guess the blackened right — and the killer alone is punished. Guess WRONG—" },
    { s:"static", who:"STATIC", t:"—and the killer walks free, while the rest of you get cancelled. Permanently. Off the air!" },
    { s:"asher", who:"Asher Finn", t:"It's a closed system. Cameras everywhere, no exits, no off switch. I counted. I counted twice." },
    { s:"rex", who:"Rex Montgomery", t:"Define 'get away with it.' Burden of proof on the accuser, or the accused? Because that materially changes the game theory." },
    { s:"static", who:"STATIC", t:"Ohhh, I LIKE you. On the accuser, Bastard. Now — the mics are hot. Try not to bore me." },
    { t:"STATIC's recording light blinks, slow and patient, like it has all the time in the world." },
    { s:"protagonist", who:"You", t:"(Twenty strangers, every one of them a weapon. And a hole where my own name for myself should be.)" },
    { s:"protagonist", who:"You", t:"(I don't know what I'm the Ultimate of. But I know I'm going to figure out who did this — before it figures out me.)" },
    { go:"meet" },
  ],

  // -------------------------------------------------------------- MEET CAST
  meet: [
    { bg:"bg-studio" },
    { t:"In the long first hours, you take stock of the people you're trapped with. A few introduce themselves. Most just let you watch." },
    { s:"tanya", who:"Tanya \"T-Bone\" Jenkins", t:"There's a whole pantry back there. Industrial. You believe that? Whatever happens, we ain't starving." },
    { s:"declan", who:"Declan Cross", t:"There's also a bar. Fully stocked. I'd tell you to stay away from it, but nobody ever listens." },
    { s:"imogen", who:"Imogen Crane", t:"(leaning close, a breath against your ear) You're cataloguing exits and faces. Smart. Lonely, but smart." },
    { s:"sabrina", who:"Sabrina Finch", t:"Don't mind her. Come here, let me get a good look at you — oh, you're going to be one of my favorites, I can already tell." },
    { s:"protagonist", who:"You", t:"(Every word out of her mouth feels true and rehearsed at the same time.)" },
    { t:"You'll learn the rest of them soon enough. STATIC is in no hurry. STATIC, you're starting to understand, enjoys the waiting most of all." },
    { s:"static", who:"STATIC", t:"Settle in, cast! Get to know each other. The chemistry is EVERYTHING. Dead air is the only thing I can't forgive." },
    { t:"You can review the full roster any time from the cast gallery. For now, the studio settles into an uneasy quiet." },
    { t:"FREE TIME. Before anything happens, there's still time to get to know them — all of them, while they're all still here. You have a few moments to spend each break. Choose carefully. Some chances don't come twice." },
    { flag:"prologueDone" },
    { unlock:"freetime" },
    { slots:3 },
    { end:true },
  ],

  // -------------------------------------------------------------- DAILY LIFE / MOTIVE
  daily1: [
    { bg:"bg-night" },
    { t:"DAY THREE. No one has slept much. The studio has a way of making the dark feel recorded." },
    { t:"Then STATIC delivers the first motive — slid under every door on a single index card." },
    { s:"static", who:"STATIC", t:"RATINGS ARE FLAT, people! So here's a little incentive. In 48 hours, I release one private recording of each of you to everyone else. Your worst moment. Your real one." },
    { s:"static", who:"STATIC", t:"Unless, of course, the show gets... interesting before then. A body would be SO interesting." },
    { s:"maeve", who:"Maeve Harrow", t:"He's monetizing secrets. That's my whole act. I'm almost offended." },
    { s:"tanya", who:"Tanya \"T-Bone\" Jenkins", t:"Pfft. Mine's just gonna be me eating. Joke's on him." },
    { t:"But you catch it — the flicker. The way her laugh lands a half-beat late. Whatever's on Tanya's tape, it isn't dinner." },
    { bg:"bg-bar" },
    { t:"That night you can't sleep, so you drift toward the only warm light left on: the bar." },
    { t:"Declan is there, of course. Polishing a glass he's already polished. And Tanya is perched on a stool, talking at him without pause, the way she does." },
    { s:"tanya", who:"Tanya", t:"C'mon, Declan, one for the road! You're the Ultimate Mixologist and you've never made ME anything. That's basically an insult." },
    { s:"declan", who:"Declan", t:"It's a kindness. Go to bed, Tanya." },
    { s:"tanya", who:"Tanya", t:"Make me one and I will. I'll drink anything you put in front of me. That's a promise." },
    { s:"protagonist", who:"You", t:"(He stares at her for a long moment. Something moves behind his eyes that I don't have a name for yet.)" },
    { s:"declan", who:"Declan", t:"...Fine. One. Then everyone goes to bed and I never do this again." },
    { t:"You leave them to it. The last thing you hear is ice against glass, and Tanya laughing, delighted to have finally won something." },
    { t:"You should have stayed." },
    { go:"discovery" },
  ],

  // -------------------------------------------------------------- THE BODY
  discovery: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"DING DONG! A body has been discovered! Cast to the bar, cast to the bar — we are LIVE, baby!" },
    { sfx:"shake" },
    { bg:"bg-bar" },
    { t:"Tanya is slumped at the end of the bar, cheek to the wood, an empty lowball glass tipped over by her open hand. She is not asleep." },
    { s:"jasmine", who:"Jasmine", t:"(perfectly composed) Don't touch anything. We'll need it exactly as it is." },
    { s:"nyx", who:"Nyx Valerius", t:"(crouching, unbothered) She's been gone perhaps two hours. No wound. No struggle. Her color's wrong." },
    { s:"nyx", who:"Nyx", t:"This is poison. Almost certainly something she drank." },
    { t:"Every head in the room turns, slowly, toward the man behind the bar." },
    { s:"declan", who:"Declan", t:"(very quietly) ...I knew it. I knew I'd be the one." },
    { s:"asher", who:"Asher", t:"That's not a denial. Anyone else notice that's not a denial?" },
    { s:"static", who:"STATIC", t:"You've got the run of the studio to investigate, kittens. Then — the CLASS TRIAL. Find me my killer, or I find you all an ending." },
    { s:"protagonist", who:"You", t:"(The loudest, most alive person here went silent first. And the only suspect is already grieving himself.)" },
    { s:"protagonist", who:"You", t:"(Don't assume. Look. Collect the truth, piece by piece.)" },
    { go:"investigate1" },
  ],

  // -------------------------------------------------------------- INVESTIGATION
  investigate1: [
    { bg:"bg-bar" },
    { t:"INVESTIGATION — examine everything. Gather the Truth Bullets you'll need in the trial. Visit all the spots, then begin." },
    { investigate:"case1" },
    { go:"trial1_intro" },
  ],

  // -------------------------------------------------------------- TRIAL INTRO
  trial1_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"And we're LIVE in five, four, three—" },
    { t:"The floor drops into a ring of podiums, one for each of you, one draped in black with Tanya's photo crossed out in red. The ON AIR sign blazes." },
    { s:"static", who:"STATIC", t:"This is a CLASS TRIAL! Discuss the case, find the contradictions, and vote for the blackened. Get it right, and only the killer pays." },
    { s:"rex", who:"Rex", t:"Then let's be rigorous. The prosecution's case writes itself: Declan made the drink, Declan hates everyone, Declan barely denied it. Quod erat demonstrandum." },
    { s:"declan", who:"Declan", t:"(flat) Sure. Vote me out. I told you I was poison. I've been telling everyone that for years." },
    { s:"protagonist", who:"You", t:"(He's not defending himself. He WANTS this. That's exactly why I can't let the room take the easy answer.)" },
    { s:"protagonist", who:"You", t:"(Listen for the statement that doesn't fit the evidence. Aim the truth at the lie.)" },
    { trial:"case1" },
    { go:"verdict1" },
  ],

  // -------------------------------------------------------------- VERDICT
  verdict1: [
    { bg:"bg-trial" },
    { s:"protagonist", who:"You", t:"It wasn't a murder. It was the opposite of one — and that's the cruelest part." },
    { s:"declan", who:"Declan", t:"...Stop. Don't." },
    { s:"protagonist", who:"You", t:"Tanya said it herself: 'I'll drink anything you put in front of me.' She meant it as a joke. As trust. Declan heard it as a dare he couldn't survive." },
    { s:"protagonist", who:"You", t:"You didn't poison her to escape, Declan. You poisoned her because she got close, and you've spent your whole life certain that anyone who gets close to you dies of it." },
    { s:"protagonist", who:"You", t:"You made yourself into the thing you swore you already were. The crack was the glass — you remembered her order in too much detail. Bitters, no garnish, exactly enough of the thing that killed her. A man who doesn't care doesn't measure that carefully." },
    { s:"declan", who:"Declan", t:"(a long silence) ...She trusted the glass. That was her only crime. And I proved her wrong, the way I always knew I would." },
    { s:"static", who:"STATIC", t:"The cast has voted! And the cast is — CORRECT! The blackened who served the last call: Declan Cross!" },
    { sfx:"glitch" },
    { s:"declan", who:"Declan", t:"Don't waste your grief on me. I'd have been the death of every one of you eventually. At least this way it was quick." },
    { go:"execution1" },
  ],

  // -------------------------------------------------------------- EXECUTION (stylized)
  execution1: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"It's time for the part the audience tunes in for! Declan Cross — your last call!" },
    { sfx:"shake" },
    { execArt:"declan", title:"LAST CALL" },
    { t:"EXECUTION: LAST CALL." },
    { t:"A spotlight. An enormous, gleaming bar that stretches to a vanishing point. Declan, alone behind it, bound to make one final drink." },
    { t:"Bottle after bottle pours itself into a glass the size of a man. He works without expression, the way he always said he would — precise, contemptuous, alone." },
    { t:"The light goes out on the ON AIR sign. The studio holds its breath. And then it is very, very quiet at the bar." },
    { bg:"bg-night" },
    { t:"Nobody speaks for a long time." },
    { s:"sienna", who:"Sienna", t:"(softly, and for once she is not narrating) ...He remembered all of our orders. Every one." },
    { s:"protagonist", who:"You", t:"(One down. The loudest and the loneliest, both gone in a single night. And nineteen of us left to learn what we're capable of.)" },
    { s:"static", who:"STATIC", t:"GREAT television, everybody! Truly. Rest up — the ratings only go one direction from here." },
    { go:"hub_intro" },
  ],

  // -------------------------------------------------------------- FREE TIME HUB
  hub_intro: [
    { bg:"bg-night" },
    { t:"In the hollow days that follow, the survivors do the only thing left to do between bodies: they try to know each other." },
    { t:"FREE TIME. Spend time with the cast. Every route is one wound, cracked open by love instead of pressure — the same act the murder would have been, aimed the other way." },
    { flag:"ch1done" },
    { unlock:"freetime" },
    { slots:3 },
    { end:true },
  ],

  // ============================================================ CHAPTER 3
  //  "The Voice" — Victim: Rex.  Blackened: Itsuki.  Framed: Silas.
  ch3_intro: [
    { bg:"bg-studio" },
    { t:"CHAPTER 3 — \"THE VOICE.\"  Two more bodies came and went between then and now. The studio has learned to keep score." },
    { t:"At 8:00 PM, STATIC unveils the chapter's pressure." },
    { s:"static", who:"STATIC", t:"New segment, darlings! The TRUTH RECORDER. In forty-eight hours I play one clip of each of you over the PA — alone, unguarded, being who you ACTUALLY are. No performance. No bit. The real voice." },
    { t:"For most of the cast it's a humiliation. For the performers, it's a loaded gun." },
    { s:"itsuki", who:"Itsuki Endo", t:"(very lightly, in someone else's bright voice) Oh, fun. Can't wait to hear myself." },
    { s:"protagonist", who:"You", t:"(He's smiling in a voice that isn't his. And under it, for half a second, there's nothing at all.)" },
    { bg:"bg-night" },
    { t:"Rex has spent the whole chapter circling Itsuki like a dog with a bone — the voice actor is the most interesting puzzle in the building, and Rex cannot leave a deduction unspoken." },
    { s:"rex", who:"Rex Montgomery", t:"I've cracked you, you know. The recording's going to be silence. There's no one in there. And I'm going to say so — out loud — before the bear gets the chance." },
    { s:"itsuki", who:"Itsuki", t:"(a long, flat pause) ...That's a hell of a thing to say to a man, Rex." },
    { t:"Rex means it as a flex. It's a death sentence. His own." },
    { go:"ch3_discovery" },
  ],

  ch3_discovery: [
    { bg:"bg-dark" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"DING DONG! A body has been discovered! AV wing, kittens — and oh, this one's GOOD." },
    { sfx:"shake" },
    { bg:"bg-studio" },
    { s:"fiona", who:"Fiona Slate", t:"It's Rex. The recording booth. I do my rounds on a fixed loop — I passed at 10:15 and heard him screaming at Silas, plain as anything. Came back at 10:50, the door was open, and..." },
    { s:"silas", who:"Silas Thorne", t:"(noir cadence, unwavering) Easy now, doll. I never laid a hand on the kid. I've been framed slicker than a three-card draw." },
    { s:"jasmine", who:"Jasmine", t:"You were the last voice with him, Silas. You have no alibi. And you can't even drop the act to deny it like a human being." },
    { s:"protagonist", who:"You", t:"(The whole room is thirty seconds from convicting Silas. Which is exactly why I'm not going to take the obvious answer. Look first.)" },
    { go:"ch3_investigate" },
  ],

  ch3_investigate: [
    { bg:"bg-studio" },
    { t:"INVESTIGATION — the recording booth, the body, the studio drive. Examine every spot, then begin the trial." },
    { clearBullets:true },
    { investigate:"case3" },
    { go:"ch3_trial_intro" },
  ],

  ch3_trial_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"LIVE again! You know the drill. The room wants Silas. Prove them right — or prove them wrong." },
    { s:"protagonist", who:"You", t:"(A voice was the last thing anyone heard from Rex. The whole case is whether a voice is proof a person was alive. Let's find out.)" },
    { trial:"case3" },
    { go:"ch3_verdict" },
  ],

  ch3_verdict: [
    { bg:"bg-trial" },
    // --- Rebuttal showdown: Itsuki becomes everyone ---
    { t:"REBUTTAL SHOWDOWN. Itsuki smiles. And then he comes apart into everyone." },
    { s:"itsuki", who:"Itsuki", t:"(in YOUR voice — pitch-perfect, warm, wounded) You don't actually believe this, do you? Come on. You KNOW me—" },
    { s:"itsuki", who:"Itsuki", t:"(snapping into Rex — alive, smug, insufferable) Relax, would you? I'm fine. Cite your source, detective, you've got nothing—" },
    { s:"itsuki", who:"Itsuki", t:"(a small, trembling voice no one has heard from him) I couldn't — I would never hurt anyone — please, you have to—" },
    { s:"itsuki", who:"Itsuki", t:"(now a grieving friend, cracking on cue) He was my FRIEND. You think I could sit in that booth with his body—" },
    { s:"sabrina", who:"Sabrina", t:"(almost admiring, almost afraid) He's wearing us. One at a time. He'll be whoever each of us can't bear to convict." },
    { s:"leo", who:"Leo", t:"(hoarse, white-faced) Stop it. Stop — pick one. Pick a fucking ONE." },
    // --- Speak as yourself ---
    { s:"protagonist", who:"You", t:"Itsuki. Stop. Defend yourself — right now, in your OWN voice. Not mine. Not Rex's. Not some stranger you invented. Just you." },
    { t:"Silence. And it stretches. The same silence from the quiet room, where you once asked him this exact thing and he bolted." },
    { t:"He doesn't bolt now. There's nowhere left. His mouth opens." },
    { s:"itsuki", who:"Itsuki", t:"(flat. no color. no music. no one home.) ...What do you want me to say." },
    { t:"The room goes very, very still. That's it. That's the voice — the one the Truth Recorder was going to broadcast in forty-eight hours. The nothing under the masks." },
    { s:"itsuki", who:"Itsuki", t:"(the same dead register, every word the same weight) Rex figured it out. That there's nothing in here. He was going to stand up and SAY it. Make it a joke, before the bear could even play the tape." },
    { s:"itsuki", who:"Itsuki", t:"I could survive being empty. (a long, level pause) I couldn't survive everyone KNOWING I was empty." },
    { s:"itsuki", who:"Itsuki", t:"So I made him quiet. Then I tried to be someone innocent instead. One more time. I've done a thousand voices. I never learned mine. This is it. There's no more of it than this." },
    // --- Verdict ---
    { s:"static", who:"STATIC", t:"UPUPU — he SANG! On his very own voice, no backup track! Cast your votes, kittens — though honestly, after that, do we even need to?" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"Dingdingding! The blackened is the Ultimate Voice Actor — ITSUKI ENDO! Time for his solo!" },
    { s:"silas", who:"Silas", t:"(to the floor — and for half of one syllable the drawl falls clean off the word before he catches it) ...Kid saved my life by trying to wear me. (it's back instantly, the bunker sealing) ...World's a funny, mean little town, doll." },
    { s:"sienna", who:"Sienna", t:"(soft, transfixed, reaching again for a recorder she doesn't have) A voice as a weapon. A voice as a confession. The murder weapon AND the murder AND the man... God. Somebody should be writing this down." },
    { s:"protagonist", who:"You", t:"(Nobody clocks her. They will. File it away.)" },
    { s:"leo", who:"Leo", t:"(no venom left — which from Leo is the loudest thing he's ever said) I've pretended to be a hundred people I'm not. Whole childhood. At least I always knew which one was ME." },
    { s:"leo", who:"Leo", t:"He killed a guy so none of us would find out there was no one home. And we just made him say it out loud. To a full room." },
    { t:"You say nothing. There's nothing to add. There was never a version of tonight where Itsuki Endo got to stay hidden." },
    { go:"ch3_execution" },
  ],

  ch3_execution: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"EXECUTION TIME! Itsuki Endo — break a leg. Break all of them!" },
    { sfx:"shake" },
    { execArt:"itsuki", title:"THE LAST BOOTH" },
    { t:"EXECUTION: THE LAST BOOTH." },
    { t:"Itsuki is dragged into an endless recording studio that stretches past the horizon — booth after booth after booth. A red ON AIR light flares. A script drops." },
    { t:"He voices a character. Flawless. The light dies, the booth goes dark, and the next lights up — new script, new face, new voice. Faster. Faster. A thousand strangers pouring out of one throat, each perfect, none of them him." },
    { sfx:"glitch" },
    { t:"At the very end, every screen in every booth lights up at once and plays a single recording over the infinite speakers: Itsuki, alone, in his own flat voice, saying nothing at all." },
    { t:"The Truth Recorder, finally aired — to a stadium of no one. And the lights go out for good." },
    { bg:"bg-night" },
    { s:"sienna", who:"Sienna Fox", t:"(too lit up, reaching twice for a recorder that isn't there) ...That was incredible. The structure of it. A voice became a weapon became a confession. God, what a—" },
    { s:"sienna", who:"Sienna", t:"(catching herself) ...sorry. What a waste. That's what I meant." },
    { s:"protagonist", who:"You", t:"(She doesn't realize she's auditioning for a job she'll eventually take. Neither do they. File it away.)" },
    { flag:"ch3done" },
    { go:"hub_intro" },
  ],

  // ============================================================ CHAPTER 2
  //  "What She Knew" — Victim: Maeve.  Blackened: Jasmine.
  ch2_intro: [
    { bg:"bg-studio" },
    { t:"CHAPTER 2 — \"WHAT SHE KNEW.\"  The studio has stopped pretending the quiet means safety." },
    { t:"STATIC's second motive is a single envelope, hand-delivered to each of you, sealed with wax." },
    { s:"static", who:"STATIC", t:"Inside each one, lovelies: the worst secret I could dig up about ANOTHER cast member. A gift! Do with it what you will. Knowledge is power, and power is RATINGS." },
    { s:"maeve", who:"Maeve Harrow", t:"(turning hers over, unimpressed) Amateur hour. I already know everyone's. It's the only thing I'm good for." },
    { t:"And she does. Maeve is the building's archive — every affair, every fraud, every disqualifying thing. Including, you'll learn too late, one that could cost a crown." },
    { bg:"bg-night" },
    { t:"That evening you pass the dressing room. Through the door, two voices — low, clipped." },
    { s:"maeve", who:"Maeve", t:"...I'm not threatening you, Jasmine. I'm telling you what I have. Whether it stays a secret is a conversation. I'm always willing to trade." },
    { s:"jasmine", who:"Jasmine Sterling", t:"(warm, lethal, not a hair out of place) Of course. Let's talk. Truly — I'm so glad you came to me first." },
    { s:"protagonist", who:"You", t:"(Maeve sounds like she's holding all the cards. She has no idea who she's playing.)" },
    { go:"ch2_discovery" },
  ],
  ch2_discovery: [
    { bg:"bg-dark" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"DING DONG! A body has been discovered! Dressing room, kittens. Bring your condolences and your suspicions." },
    { sfx:"shake" },
    { bg:"bg-studio" },
    { t:"Maeve is on the dressing-room floor beneath the toppled vanity mirror — a heavy, gilded thing. At a glance: a terrible accident, the mirror pulled down on top of her." },
    { s:"nyx", who:"Nyx Valerius", t:"(crouching, unhurried) Blunt force to the temple. Hm. The mirror, supposedly. (a pause) Supposedly." },
    { s:"jasmine", who:"Jasmine", t:"(immaculate, grave) How awful. She must have leaned on it. I was on stage rehearsing all evening — the cameras will show it. Poor thing." },
    { s:"protagonist", who:"You", t:"(She offered her alibi before anyone asked for it. And the scene is too neat. Look closer.)" },
    { go:"ch2_investigate" },
  ],
  ch2_investigate: [
    { bg:"bg-studio" },
    { t:"INVESTIGATION — the dressing room, the body, the stage footage. Examine every spot, then begin the trial." },
    { clearBullets:true },
    { investigate:"case2" },
    { go:"ch2_trial_intro" },
  ],
  ch2_trial_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"LIVE! This culprit won't panic, won't confess, won't crack. Catch her on the FACE? Good luck. Catch her on the math." },
    { s:"protagonist", who:"You", t:"(She rehearsed this the way she rehearses everything. So I won't look for a tell on her face. I'll look for the one record she couldn't curate.)" },
    { trial:"case2" },
    { go:"ch2_verdict" },
  ],
  ch2_verdict: [
    { bg:"bg-trial" },
    { s:"protagonist", who:"You", t:"Your alibi is the rehearsal footage. And it's real footage — just not from tonight. There's a clock reflected in the stage mirror behind you, Jasmine. It reads twenty minutes off." },
    { s:"protagonist", who:"You", t:"You curated everything. The pose, the timestamp, the grief. You couldn't curate a clock you forgot was in frame. That's the math. That's where you break — never on your face." },
    { s:"jasmine", who:"Jasmine", t:"(the smile holds, holds, holds — and then, for the first time, her hand rises to straighten a crown that is already perfectly straight)" },
    { s:"jasmine", who:"Jasmine", t:"...She was going to take it from me. The one thing I bled for. The diet, the heels that drew blood, the smile I drilled until it survived anything. Do you understand what it costs to be this?" },
    { s:"protagonist", who:"You", t:"Maeve had the secret that would cost you the crown. So you decided, calmly, that a life was an acceptable price. You never once decided the crown wasn't worth it." },
    { s:"static", who:"STATIC", t:"The cast votes — CORRECT! The blackened who never broke a sweat: Jasmine Sterling!" },
    { s:"jasmine", who:"Jasmine", t:"(composure perfect again, the crown touched back into place) Don't pity me. I'd do it again. That's not a crack. That's the only honest thing I've ever said." },
    { go:"ch2_execution" },
  ],
  ch2_execution: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"EXECUTION TIME! Jasmine Sterling — one last walk down the runway!" },
    { sfx:"shake" },
    { execArt:"jasmine", title:"FINAL CROWN" },
    { t:"EXECUTION: FINAL CROWN." },
    { t:"A blinding runway under a thousand lights. Jasmine walks it the way she's walked every stage — spine straight, smile drilled, not a hair out of place — toward a throne at the far end." },
    { t:"The crown lowers onto her head. It keeps lowering. Heavier, heavier, the lights flaring white-hot, and through all of it she does not let the smile waver, because the woman who cries loses the crown, and she has never once decided it wasn't worth it." },
    { sfx:"glitch" },
    { t:"The lights go out. The smile is the last thing to go." },
    { bg:"bg-night" },
    { s:"sabrina", who:"Sabrina", t:"(quietly) ...She held it to the end. God help her, she actually held it to the end." },
    { s:"protagonist", who:"You", t:"(The saddest sentence in this whole building: she'd have done it again. Two more gone. Keep moving.)" },
    { flag:"ch2done" },
    { go:"hub_intro" },
  ],

  // ============================================================ CHAPTER 4
  //  "Partners" — Victim: Kieran.  Blackened: Chloe + Elias.
  ch4_intro: [
    { bg:"bg-studio" },
    { t:"CHAPTER 4 — \"PARTNERS.\"  Fewer of you now. The pantry's emptier. The silences are louder." },
    { s:"static", who:"STATIC", t:"Ratings dip, motive bumps! New rule, sweethearts: this time, a TEAM can graduate. Two of you pull off a murder together, and if the trial fingers the wrong number of culprits — you BOTH walk." },
    { s:"chloe", who:"Chloe Carmichael", t:"(eyes lighting up) ...A partnership. A joint venture. Two people, aligned incentives, shared upside. (turning, slow) Elias. Sweetie. Can I talk to you about an OPPORTUNITY?" },
    { s:"elias", who:"Elias Croft", t:"(adjusting the fedora, desperate to be wanted) I mean — yeah. Yeah, totally, I'm a high-value collaborator, people say that—" },
    { bg:"bg-bar" },
    { t:"And there's Kieran behind the café counter, who has spent the whole game making both of them feel like nothing." },
    { s:"kieran", who:"Kieran Holt", t:"An MLM and a pickup 'coach' going into business together. That's not a downline, that's two drowning people selling each other water. (sneer) Bless." },
    { s:"protagonist", who:"You", t:"(He just made it personal with the two people least equipped to let an insult go. That's a dangerous thing to do in here.)" },
    { go:"ch4_discovery" },
  ],
  ch4_discovery: [
    { bg:"bg-dark" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"DING DONG! A body has been discovered! The café, darlings. And ooh — this one's MESSY." },
    { sfx:"shake" },
    { bg:"bg-bar" },
    { t:"Kieran is behind his own counter, struck down from behind. Two coffee cups sit on the bar, both used. Whoever did this, he made them drinks first — he served his killers." },
    { s:"chloe", who:"Chloe", t:"(too fast) I left ages before it happened! I made my coffee and went, Elias was still here, ask him—" },
    { s:"elias", who:"Elias", t:"(too fast) What? No — she was here the WHOLE time, I left first, I have a whole framework about not being last in a room—" },
    { s:"protagonist", who:"You", t:"(Two stories. Two cups. And the two of them tripping over each other to throw the other under the bus. ...Interesting.)" },
    { go:"ch4_investigate" },
  ],
  ch4_investigate: [
    { bg:"bg-bar" },
    { t:"INVESTIGATION — the café counter, the two cups, the conflicting stories. Examine every spot, then begin the trial." },
    { clearBullets:true },
    { investigate:"case4" },
    { go:"ch4_trial_intro" },
  ],
  ch4_trial_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"LIVE! Two cups, two stories, two suspects pointing at each other. Count carefully, kittens — the number matters this time." },
    { s:"protagonist", who:"You", t:"(They each think the smart move is to sell the other out. They're both right, and that's exactly how I catch them both.)" },
    { trial:"case4" },
    { go:"ch4_verdict" },
  ],
  ch4_verdict: [
    { bg:"bg-trial" },
    { s:"protagonist", who:"You", t:"It took two of you. One to keep Kieran talking — to run a script at him while he made the drinks — and one to come around the counter behind him. Neither could have done it alone. He was wary; he'd have seen a single person coming." },
    { s:"protagonist", who:"You", t:"And there's the recruitment sheet. Chloe pitched it as a partnership. A team win. You graduated together or not at all." },
    { s:"chloe", who:"Chloe", t:"(turning on him) You were supposed to take the fall! That was the DEAL, that was the value proposition, you said you understood the—" },
    { s:"elias", who:"Elias", t:"(turning on her) The deal was YOU'D say it was self-defense and they'd believe you because you're — you're likeable, and I — (voice cracking) you were never going to cover for me. You were never on my side." },
    { s:"protagonist", who:"You", t:"No. Neither of you was. The partnership was just two cons conning each other. The blackened are Chloe Carmichael AND Elias Croft — both of you." },
    { s:"static", who:"STATIC", t:"DINGDINGDING! Correct count, correct names! A matched set: Chloe AND Elias!" },
    { s:"chloe", who:"Chloe", t:"(very quietly, the pitch finally gone) ...I just wanted someone to say yes to me. For once. With no catch." },
    { s:"elias", who:"Elias", t:"(the fedora in his hands now, off his head) ...Yeah. (a wrecked little laugh) Me too. We had that in common the whole time and we still used it as a weapon." },
    { go:"ch4_execution" },
  ],
  ch4_execution: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"DOUBLE EXECUTION! Our first team graduation — and our first team FAILURE. Roll it!" },
    { sfx:"shake" },
    { execArt:["chloe","elias"], title:"THE PYRAMID" },
    { t:"EXECUTION: THE PYRAMID." },
    { t:"Two podiums rise at the base of an enormous golden pyramid scheme — a literal pyramid, levels stretching into the dark. Chloe is made to climb, recruiting phantom downline at every tier; Elias is made to run his script at an audience of cardboard cutouts that never, ever respond." },
    { t:"The higher Chloe climbs, the more the pyramid leans. Each tries to reach the other across the gap between their two ladders. Their fingers don't meet. The structure was never built to hold two people who were only ever using each other." },
    { sfx:"glitch" },
    { t:"It comes down all at once." },
    { bg:"bg-night" },
    { s:"rowan", who:"Rowan", t:"(no irony for once) They reached for each other at the end. After all that. That's the part that's actually messed up." },
    { s:"protagonist", who:"You", t:"(Two more. The two most desperate to be chosen, and they died learning neither ever chose the other. Keep moving.)" },
    { flag:"ch4done" },
    { go:"hub_intro" },
  ],

  // ============================================================ CHAPTER 5
  //  "Time of Death" — Victim: Asher.  Blackened: Nyx.
  ch5_intro: [
    { bg:"bg-night" },
    { t:"CHAPTER 5 — \"TIME OF DEATH.\"  Single digits now. Everyone left has watched the evidence convict someone, and started to wonder how much they trust the evidence." },
    { t:"All game, one voice has been the bedrock of every trial: Nyx, the de facto coroner. Cause of death, time of death — her word, taken as objective." },
    { s:"asher", who:"Asher Finn", t:"(low, only to you) Has it ever bothered you? We take her numbers like scripture. But she's the only one who ever touches the bodies. Who checks the checker?" },
    { s:"asher", who:"Asher", t:"And watch her hands. Steady as stone around a corpse. Around us? Shaking. A person's calmest where they feel safest. She feels safest with the dead. ...What does that tell you." },
    { s:"protagonist", who:"You", t:"(Asher's theories about the world are insane. His read on a single person is never wrong. And right now he's the only one not trusting Nyx.)" },
    { s:"nyx", who:"Nyx Valerius", t:"(from across the room, having heard none of it, watching Asher with a flat, appraising warmth) ...He has lovely bone structure. I keep meaning to tell him." },
    { go:"ch5_discovery" },
  ],
  ch5_discovery: [
    { bg:"bg-dark" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"DING DONG! A body has been discovered! And oh, this is my favorite kind — the kind where you can't even trust the autopsy." },
    { sfx:"shake" },
    { bg:"bg-studio" },
    { t:"Asher is dead in the archive room. Nyx is already kneeling over him, report half-written, when the others arrive." },
    { s:"nyx", who:"Nyx", t:"(level, certain) Time of death, eleven PM. Cause, a sedative overdose — self-administered or forced, I can't yet say. He died around eleven. I was with four of you at eleven. Make of that what you will." },
    { s:"protagonist", who:"You", t:"(She gave the time, the cause, and her own alibi in a single breath. And her hands, over Asher's body, are perfectly, perfectly steady.)" },
    { s:"protagonist", who:"You", t:"(The one man who said don't trust her findings is the body under her findings. I have to check the corpse against the coroner.)" },
    { go:"ch5_investigate" },
  ],
  ch5_investigate: [
    { bg:"bg-studio" },
    { t:"INVESTIGATION — the body, the autopsy report, Asher's notebook. The murderer controls the evidence this time. Examine every spot, then begin the trial." },
    { clearBullets:true },
    { investigate:"case5" },
    { go:"ch5_trial_intro" },
  ],
  ch5_trial_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"LIVE! Here's the twist, darlings: the witness you've trusted all game is the one on trial. When the evidence itself can lie — who do you believe?" },
    { s:"protagonist", who:"You", t:"(Believe the body. The body can't curate itself. Only the report can.)" },
    { trial:"case5" },
    { go:"ch5_verdict" },
  ],
  ch5_verdict: [
    { bg:"bg-trial" },
    { s:"protagonist", who:"You", t:"Your report says eleven PM. The body says otherwise — the lividity, the way the blood settled, all of it points hours earlier. You wrote a time of death that gave you an alibi, Nyx. You could, because you're the only one who reads the body. You lied in your own autopsy." },
    { s:"protagonist", who:"You", t:"And everyone finally saw it: the woman who shakes around the living delivered that report without a tremor. Your hands, for once, were perfectly steady — because you were home. You're only ever calm with the dead." },
    { s:"nyx", who:"Nyx", t:"(no denial; she simply sets down the pen) ...He was going to leave. Not the studio. Me. He'd decided I wasn't safe to be near, and he was going to walk away under his own power. I can't survive that. I've never been able to survive that." },
    { s:"nyx", who:"Nyx", t:"So I kept him the only way I know how. The way you keep anything you love. (softly) Still. Cooling. Unable to walk away from me ever again. He can't leave now. Do you see? It's the first time I've ever felt safe with someone warm — after I made him cold." },
    { s:"protagonist", who:"You", t:"That's the most honest and the most broken thing I've heard in this building. And it's still murder." },
    { s:"static", who:"STATIC", t:"The cast votes — CORRECT! The coroner who cooked her own books: Nyx Valerius!" },
    { go:"ch5_execution" },
  ],
  ch5_execution: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { s:"static", who:"STATIC", t:"EXECUTION TIME! Nyx Valerius — last appointment of the day!" },
    { sfx:"shake" },
    { execArt:"nyx", title:"THE LONG STILLNESS" },
    { t:"EXECUTION: THE LONG STILLNESS." },
    { t:"An endless mortuary, white and cold and quiet — the only place Nyx has ever been at ease. She moves through it almost peacefully, table after empty steel table, finally somewhere nothing can leave her." },
    { t:"And then the tables are no longer empty. Every person she ever lost. Every warm thing that walked away. They lie there, still and safe and hers at last — and she understands, too late, that this is what she built, that the only way she ever stopped being left was to stop everyone, including herself." },
    { sfx:"glitch" },
    { t:"She lies down on the last table herself, and is finally, perfectly calm. The light goes out." },
    { bg:"bg-night" },
    { s:"silas", who:"Silas", t:"(the noir gone thin and quiet) ...She wasn't cruel. That's the hell of it, see. She just loved the only way the world ever let her practice." },
    { s:"protagonist", who:"You", t:"(Down to a handful of us. And I'm starting to feel it — that none of this was random. Someone has been writing the season.)" },
    { flag:"ch5done" },
    { go:"hub_intro" },
  ],

  // ============================================================ CHAPTER 6
  //  "The Last Episode" — Mastermind: Sienna.  Not a case. An unmasking.
  ch6_intro: [
    { bg:"bg-studio" },
    { t:"CHAPTER 6 — \"THE LAST EPISODE.\"  No body this time. Just the survivors, the dead microphones, and a quiet that finally feels like an ending." },
    { s:"static", who:"STATIC", t:"Well, kittens! What a SEASON. Before the finale, your host has a confession — I was never the one running the show. I just read the lines I was given. Roll the credits and meet your PRODUCER." },
    { sfx:"glitch" },
    { t:"STATIC's recording light dims for the first time. Every survivor turns, slowly, to the one person in the room who has narrated every death like a season beat." },
    { s:"sienna", who:"Sienna Fox", t:"(she doesn't run. She just exhales, almost relieved) ...God, finally. Do you know how hard it is to not say 'previously, on—' for six straight chapters?" },
    { s:"protagonist", who:"You", t:"(She's been the editorial voice the whole time. The reaching for a recorder. The 'great episode.' I have to be able to prove it — not just feel it.)" },
    { go:"ch6_investigate" },
  ],
  ch6_investigate: [
    { bg:"bg-studio" },
    { t:"FINAL INVESTIGATION — not a crime scene, but the whole season. Gather the tells you've been collecting since Chapter 1." },
    { clearBullets:true },
    { investigate:"case6" },
    { go:"ch6_trial_intro" },
  ],
  ch6_trial_intro: [
    { bg:"bg-trial" },
    { sfx:"glitch" },
    { s:"static", who:"STATIC", t:"THE FINAL TRIAL! No murder to solve — just one question. Who's been holding the pen this whole time?" },
    { s:"protagonist", who:"You", t:"(Six chapters of evidence. Aim it at the truth one last time.)" },
    { trial:"case6" },
    { go:"ch6_finale" },
  ],
  ch6_finale: [
    { bg:"bg-trial" },
    { s:"protagonist", who:"You", t:"It was always you, Sienna. STATIC is a microphone. This whole game was a broadcast — and a broadcast has a producer. You tailored every motive. You narrated every death. You reached for a recorder at the exact moments it was, in your words, incredible content." },
    { s:"sienna", who:"Sienna", t:"(applauding, slow and genuine) Bravo. Truly. That's a finale. I've studied a thousand killings — armchair-diagnosed every one of you, called the victims 'our girl,' treated real blood like a season twist. I marinated in murder until it stopped meaning anything. So I built a show where it might mean something again." },
    { s:"sienna", who:"Sienna", t:"And it didn't. Not once. Not for me. (a flicker) ...I kept waiting for the episode where I'd feel it. It never aired." },
    { s:"protagonist", who:"You", t:"Then let's make it air now. No mic. No narration. No editorial distance. Just look at them, Sienna. The ones who are left. The ones you used as content." },
    { t:"You stop performing the prosecution. You just say their names. Tanya, who'd drink anything she was handed. Declan, who knew every order. Maeve, who only wanted to be wanted. Rex. Itsuki. Chloe. Elias. Asher. Nyx. People. Not beats." },
    { s:"sienna", who:"Sienna", t:"(reaching, by pure reflex, for the recorder that isn't there — and this time her hand closes on nothing, and stays empty)" },
    { s:"sienna", who:"Sienna", t:"...I don't. I don't have a line for this. I always have a line. (her voice goes, all at once, the way detachment shatters when it's finally real) ...Oh. Oh, god. They're not coming back. I did that. Those were — those were people, and I—" },
    { t:"For the first time in the entire game, Sienna Fox has no line prepared. She just cries, ugly and unscripted, the show finally over the moment it became true." },
    { s:"protagonist", who:"You", t:"That's the episode. The one you were waiting for. It only ever airs once, and it costs everything, and that's what it was supposed to cost the whole time." },
    { s:"static", who:"STATIC", t:"(light guttering) ...Huh. Dead air. The one thing I could never forgive. (fainter) ...and somehow it's the best thing we ever broadcast. Signing... off..." },
    { go:"ch6_end" },
  ],
  ch6_end: [
    { bg:"bg-dark" },
    { sfx:"flash" },
    { t:"The ON AIR sign dies. The padded walls stop recording. The locks, for the first time, are just locks." },
    { bg:"bg-night" },
    { t:"The survivors walk out into a light none of them recognize — fewer than they came in, carrying every name they couldn't save." },
    { s:"protagonist", who:"You", t:"(I never did remember what I was the Ultimate of. Maybe it was this: being the one pair of eyes the building couldn't fool. The one who kept aiming the truth at the lie until the broadcast finally went dark.)" },
    { flag:"ch6done" },
    { unlock:"freetime" },
    { epilogue:true },
  ],
};

// Closing card shown after the full season is complete.
const OUTRO = [
  { bg:"bg-dark" },
  { t:"STATIC — FULL SEASON COMPLETE." },
  { t:"Six cases. Last Call. What She Knew. The Voice. Partners. Time of Death. The Last Episode." },
  { t:"Eleven names you couldn't all save, and a narrator who finally felt one of them." },
  { t:"Twenty Ultimates. Twenty wounds. One machine where the dating sim and the killing game were never two games at all — every murder was a Free Time route aimed the wrong way." },
  { t:"Thank you for playing STATIC." },
  { end:true },
];

if (typeof module !== "undefined") module.exports = { STORY, OUTRO };
